#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

data = json.load(sys.stdin)
agent.set_env("TRAEFIK_HOST", data["host"])
agent.set_env("TRAEFIK_LETS_ENCRYPT", data.get("lets_encrypt", False))
agent.set_env("LDAP_DOMAIN", data.get("ldap_domain", ""))
agent.set_env("LDAP_ADMIN_GROUP", data.get("ldap_admin_group", ""))
agent.set_env("INDEX_UNCLASSIFIED_EVENTS", data.get("index_unclassified_events", False))
agent.set_env("EXPORT_URL", data.get("export_url", ""))
