#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

data = json.load(sys.stdin)
agent.set_env("TRAEFIK_HOST", data["host"])
agent.set_env("TRAEFIK_LETS_ENCRYPT", data.get("lets_encrypt", False))
