#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e
exec 1>&2

systemctl --user enable wazuh.service
# Starting the pod does not start the children, so list them all, in order
systemctl --user restart wazuh.service wazuh-indexer.service wazuh-manager.service wazuh-dashboard.service
