#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "lets_encrypt": os.environ["TRAEFIK_LETS_ENCRYPT"] == "True",
    "host": os.environ["TRAEFIK_HOST"],
    "ldap_domain": os.environ.get("LDAP_DOMAIN", ""),
    "ldap_admin_group": os.environ.get("LDAP_ADMIN_GROUP", ""),
    "ldap_readonly_group": os.environ.get("LDAP_READONLY_GROUP", ""),
    "index_unclassified_events": os.environ.get("INDEX_UNCLASSIFIED_EVENTS") == "True",
    "export_url": os.environ.get("EXPORT_URL", ""),
    # Clones of instances configured before the switch existed sent emails as soon as a recipient was set
    "notify_enabled": os.environ.get("NOTIFY_ENABLED", str(bool(os.environ.get("NOTIFY_RECIPIENTS")))) == "True",
    "notify_recipients": [r for r in os.environ.get("NOTIFY_RECIPIENTS", "").split(",") if r],
    "notify_sender": os.environ.get("NOTIFY_SENDER", ""),
    "notify_min_level": os.environ.get("NOTIFY_MIN_LEVEL", "medium"),
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
