#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent

# Ports used by the Wazuh agents: events, enrollment and the TLS listener
agent.add_public_service(os.environ["MODULE_ID"], [
    "1514/tcp",
    "1515/tcp",
    "1517/tcp",
])
