#!/bin/bash

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# The cluster smarthost changed: apply it to the email channel, or remove the channel when it is disabled

set -e
exec 1>&2

runagent provision-notifications
