#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e
exec 1>&2

systemctl --user enable --now send-findings-export.timer send-findings-email.timer
systemctl --user try-restart wazuh.service wazuh-indexer.service wazuh-manager.service wazuh-dashboard.service
