#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import agent

# Close the agent ports opened by create-module
agent.remove_public_service(os.environ["MODULE_ID"])
