#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)
renv = request['environment']

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "host": renv["TRAEFIK_HOST"],
    "lets_encrypt": renv["TRAEFIK_LETS_ENCRYPT"] == "True",
    "ldap_domain": renv["LDAP_DOMAIN"],
    "ldap_admin_group": renv["LDAP_ADMIN_GROUP"],
    "ldap_readonly_group": renv.get("LDAP_READONLY_GROUP", ""),
    "index_unclassified_events": renv["INDEX_UNCLASSIFIED_EVENTS"] == "True",
    "export_url": renv["EXPORT_URL"],
    "notify_enabled": renv.get("NOTIFY_ENABLED", str(bool(renv.get("NOTIFY_RECIPIENTS")))) == "True",
    "notify_recipients": [r for r in renv.get("NOTIFY_RECIPIENTS", "").split(",") if r],
    "notify_sender": renv.get("NOTIFY_SENDER", ""),
    "notify_min_level": renv.get("NOTIFY_MIN_LEVEL", "medium"),
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
